version: '3'
services:
  frontend:
    image: node:14
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    command: npm start
    ports:
      - "3000:3000"

  backend:
    image: node:14
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
    command: npm start
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
